import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

// ============================================================
// Supabase setup
// ============================================================
const SUPABASE_URL = 'https://tltewglxvxdymumuknpo.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_2dqRVNmrZQJR2T5kIe8xNw_c3sZdBuu';
const sb = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {});
  });
}


// ============================================================
// Toast
// ============================================================
let toastTimer;
function toast(msg, isError) {
  const el = document.getElementById('toast');
  el.textContent = msg;
  el.classList.remove('hidden');
  el.style.background = isError ? '#8c2a2a' : '#241F1B';
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => el.classList.add('hidden'), 3800);
}

// ============================================================
// Auth + identity
// ============================================================
let currentUser = null;     // supabase auth user
let currentProfile = null;  // { id, display_name }

function initials(name) {
  return (name || '?').trim().split(/\s+/).slice(0, 2).map(w => w[0]?.toUpperCase() || '').join('') || '?';
}

function renderWhoAmI() {
  const nameEl = document.getElementById('whoamiName');
  const avatarEl = document.getElementById('whoamiAvatar');
  if (currentProfile) {
    nameEl.textContent = currentProfile.display_name;
    avatarEl.textContent = initials(currentProfile.display_name);
  } else {
    nameEl.textContent = 'a guest';
    avatarEl.textContent = '?';
  }
}

document.getElementById('editNameBtn').addEventListener('click', async () => {
  if (!currentProfile) return;
  const n = prompt("What's your name?", currentProfile.display_name || '');
  if (n && n.trim()) {
    const { error } = await sb.from('profiles').update({ display_name: n.trim() }).eq('id', currentProfile.id);
    if (error) { toast('Could not update your name.', true); return; }
    currentProfile.display_name = n.trim();
    renderWhoAmI();
  }
});

document.getElementById('signOutBtn').addEventListener('click', async () => {
  await sb.auth.signOut();
});

// ----- Gate UI -----
const gateEl = document.getElementById('gate');
const appRootEl = document.getElementById('appRoot');

function showGateStep(step) {
  ['email', 'sent', 'name'].forEach(s => {
    document.getElementById(`gateStep-${s}`).classList.toggle('hidden', s !== step);
  });
}

document.getElementById('gateEmailForm').addEventListener('submit', async (e) => {
  e.preventDefault();
  const email = document.getElementById('gateEmailInput').value.trim();
  if (!email) return;
  const statusEl = document.getElementById('gateStatus');
  const btn = document.getElementById('gateSendBtn');
  btn.disabled = true;
  statusEl.classList.add('hidden', 'error');
  try {
    const { error } = await sb.auth.signInWithOtp({
      email,
      options: { emailRedirectTo: window.location.origin }
    });
    if (error) throw error;
    document.getElementById('gateSentEmail').textContent = email;
    showGateStep('sent');
  } catch (err) {
    statusEl.textContent = err.message || 'Could not send the link. Try again.';
    statusEl.classList.remove('hidden');
    statusEl.classList.add('error');
  } finally {
    btn.disabled = false;
  }
});

document.getElementById('gateBackBtn').addEventListener('click', () => showGateStep('email'));

document.getElementById('gateNameForm').addEventListener('submit', async (e) => {
  e.preventDefault();
  const name = document.getElementById('gateNameInput').value.trim();
  if (!name || !currentUser) return;
  const { error } = await sb.from('profiles').update({ display_name: name }).eq('id', currentUser.id);
  if (error) { toast('Could not save your name.', true); return; }
  currentProfile.display_name = name;
  enterApp();
});

async function loadOrCreateProfile(user) {
  let { data, error } = await sb.from('profiles').select('*').eq('id', user.id).maybeSingle();
  if (error) { toast('Could not load your profile.', true); return null; }
  if (!data) {
    // Trigger may not have fired yet (race on very first sign-in) — create it ourselves.
    const fallbackName = (user.email || 'member').split('@')[0];
    const { data: inserted, error: insErr } = await sb.from('profiles')
      .insert({ id: user.id, display_name: fallbackName })
      .select().single();
    if (insErr) { toast('Could not set up your profile.', true); return null; }
    data = inserted;
  }
  return data;
}

function looksAutoGenerated(displayName, email) {
  if (!displayName || !email) return false;
  return displayName.toLowerCase() === email.split('@')[0].toLowerCase();
}

async function enterApp() {
  gateEl.classList.add('hidden');
  appRootEl.classList.remove('hidden');
  renderWhoAmI();
  renderHeroDate();
  loadReadings();
  loadDevotional();
  loadGuides();
  loadIdeas();
  loadPrayerRequests();
  loadHomework();
  loadCalendarEvents();
  loadPhotos();
  loadContacts();
}

async function handleSession(session) {
  if (!session) {
    currentUser = null;
    currentProfile = null;
    appRootEl.classList.add('hidden');
    gateEl.classList.remove('hidden');
    showGateStep('email');
    return;
  }
  currentUser = session.user;
  currentProfile = await loadOrCreateProfile(currentUser);
  if (!currentProfile) return;

  if (looksAutoGenerated(currentProfile.display_name, currentUser.email)) {
    gateEl.classList.remove('hidden');
    showGateStep('name');
    return;
  }
  enterApp();
}

sb.auth.onAuthStateChange((_event, session) => { handleSession(session); });
sb.auth.getSession().then(({ data }) => handleSession(data.session));

// ============================================================
// Tab navigation
// ============================================================
const tabs = ['home', 'readings', 'devotional', 'guides', 'ideas', 'prayer', 'homework', 'calendar', 'photos', 'contacts'];
function gotoTab(tab) {
  tabs.forEach(t => {
    document.getElementById(`panel-${t}`).classList.toggle('is-active', t === tab);
  });
  document.querySelectorAll('.nav-item').forEach(btn => {
    btn.classList.toggle('is-active', btn.dataset.tab === tab);
  });
  window.scrollTo({ top: 0 });
}
document.getElementById('nav').addEventListener('click', (e) => {
  const btn = e.target.closest('.nav-item');
  if (btn) gotoTab(btn.dataset.tab);
});
document.querySelectorAll('[data-goto]').forEach(el => {
  el.addEventListener('click', () => gotoTab(el.dataset.goto));
});

// ============================================================
// Liturgical calendar math
// ============================================================
function computeEaster(year) {
  const a = year % 19, b = Math.floor(year / 100), c = year % 100;
  const d = Math.floor(b / 4), e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4), k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31);
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return new Date(year, month - 1, day);
}
function addDays(date, n) {
  const d = new Date(date);
  d.setDate(d.getDate() + n);
  return d;
}
function nearestSunday(date) {
  const dow = date.getDay();
  const offset = dow <= 3 ? -dow : (7 - dow);
  return addDays(date, offset);
}
function ymd(date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
}
function dateKey(y, m, d) { return `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`; }

// Fixed-date solemnities / feasts (month, day, name, isHolyDay)
const FIXED_FEASTS = [
  [1, 1, "Mary, Mother of God", true],
  [1, 6, "Epiphany (traditional date)", false],
  [2, 2, "Presentation of the Lord (Candlemas)", false],
  [3, 19, "St. Joseph", false],
  [3, 25, "Annunciation of the Lord", false],
  [5, 1, "St. Joseph the Worker", false],
  [6, 24, "Nativity of St. John the Baptist", false],
  [6, 29, "Sts. Peter and Paul", false],
  [7, 16, "Our Lady of Mount Carmel", false],
  [8, 6, "Transfiguration of the Lord", false],
  [8, 15, "Assumption of Mary", true],
  [8, 22, "Queenship of Mary", false],
  [9, 8, "Nativity of Mary", false],
  [9, 14, "Exaltation of the Holy Cross", false],
  [9, 29, "Sts. Michael, Gabriel & Raphael", false],
  [10, 7, "Our Lady of the Rosary", false],
  [11, 1, "All Saints", true],
  [11, 2, "All Souls", false],
  [11, 9, "Dedication of the Lateran Basilica", false],
  [11, 21, "Presentation of Mary", false],
  [11, 30, "St. Andrew the Apostle", false],
  [12, 8, "Immaculate Conception", true],
  [12, 12, "Our Lady of Guadalupe", false],
  [12, 25, "Christmas", true],
  [12, 26, "St. Stephen", false],
  [12, 28, "Holy Innocents", false],
];

function movableFeasts(year) {
  const easter = computeEaster(year);
  return [
    { date: addDays(easter, -46), name: "Ash Wednesday", holyDay: false },
    { date: addDays(easter, -7), name: "Palm Sunday", holyDay: false },
    { date: addDays(easter, -3), name: "Holy Thursday", holyDay: false },
    { date: addDays(easter, -2), name: "Good Friday", holyDay: false },
    { date: easter, name: "Easter Sunday", holyDay: false },
    { date: addDays(easter, 39), name: "Ascension of the Lord", holyDay: true },
    { date: addDays(easter, 49), name: "Pentecost", holyDay: false },
    { date: addDays(easter, 56), name: "Trinity Sunday", holyDay: false },
    { date: addDays(easter, 63), name: "Corpus Christi", holyDay: false },
  ];
}

function adventStart(year) {
  return nearestSunday(new Date(year, 10, 30)); // Sunday nearest Nov 30
}

// Returns { season, color, label } for a given date
function liturgicalInfo(date) {
  const y = date.getFullYear();
  const easterThis = computeEaster(y);
  const ashWed = addDays(easterThis, -46);
  const pentecost = addDays(easterThis, 49);
  const advent = adventStart(y);
  const christmas = new Date(y, 11, 25);
  const christmasPrevYear = new Date(y - 1, 11, 25);
  const baptismOfLord = addDays(new Date(y, 0, 6), 7); // rough: ~ a week after Epiphany

  const t = date.getTime();

  if (t >= christmasPrevYear.getTime() && t < baptismOfLord.getTime()) {
    return { season: 'Christmas', color: '#b8912f', dot: '#b8912f' };
  }
  if (t >= advent.getTime() && t < christmas.getTime()) {
    return { season: 'Advent', color: '#5b3a73', dot: '#5b3a73' };
  }
  if (t >= ashWed.getTime() && t < easterThis.getTime()) {
    return { season: 'Lent', color: '#5b3a73', dot: '#5b3a73' };
  }
  if (t >= easterThis.getTime() && t <= pentecost.getTime()) {
    return { season: 'Easter', color: '#b8912f', dot: '#b8912f' };
  }
  return { season: 'Ordinary Time', color: '#3f6e4e', dot: '#3f6e4e' };
}

function feastsForYear(year) {
  const list = [];
  FIXED_FEASTS.forEach(([m, d, name, holyDay]) => {
    list.push({ date: new Date(year, m - 1, d), name, holyDay, fixed: true });
  });
  movableFeasts(year).forEach(f => list.push({ date: f.date, name: f.name, holyDay: f.holyDay, fixed: false }));
  list.push({ date: adventStart(year), name: "First Sunday of Advent", holyDay: false, fixed: false });
  return list;
}
function feastsOnDate(date) {
  const year = date.getFullYear();
  const key = ymd(date);
  return feastsForYear(year).filter(f => ymd(f.date) === key);
}

// ============================================================
// Home hero + daily readings
// ============================================================
function uscbbUrl(date) {
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  const yy = String(date.getFullYear()).slice(-2);
  return `https://bible.usccb.org/bible/readings/${mm}${dd}${yy}.cfm`;
}

function renderHeroDate() {
  const today = new Date();
  const info = liturgicalInfo(today);
  document.documentElement.style.setProperty('--season', info.color);
  document.documentElement.style.setProperty('--season-soft', info.color + '1a');

  const dateStr = today.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
  document.getElementById('heroDate').textContent = dateStr;
  document.getElementById('heroSeason').textContent = info.season;

  const feasts = feastsOnDate(today);
  document.getElementById('heroFeast').textContent = feasts.length
    ? feasts.map(f => f.name + (f.holyDay ? ' (Holy Day of Obligation)' : '')).join(' · ')
    : "No major feast today — an ordinary day for extraordinary faith.";

  const url = uscbbUrl(today);
  document.getElementById('heroReadingsBtn').href = url;

  document.getElementById('readingsDate').textContent = dateStr;
  document.getElementById('readingsSeason').textContent = info.season + (feasts.length ? ' · ' + feasts.map(f => f.name).join(', ') : '');
}

// ============================================================
// Daily Readings (citations from USCCB, text from a public-domain translation)
// ============================================================
async function loadReadings() {
  const bodyEl = document.getElementById('readingsBody');
  bodyEl.innerHTML = `<div class="empty-state">Loading today's readings…</div>`;
  const today = new Date();
  const mmddyy = `${String(today.getMonth() + 1).padStart(2, '0')}${String(today.getDate()).padStart(2, '0')}${String(today.getFullYear()).slice(-2)}`;
  document.getElementById('readingsLink').href = uscbbUrl(today);

  try {
    const { data: { session } } = await sb.auth.getSession();
    const res = await fetch(`/.netlify/functions/daily-readings?date=${mmddyy}`, {
      headers: { 'Authorization': `Bearer ${session?.access_token || ''}` }
    });
    const data = await res.json();
    if (!res.ok || !data.sections || !data.sections.length) {
      bodyEl.innerHTML = `<div class="empty-state">Couldn't load today's readings. Use the link below to read them at USCCB.org.</div>`;
      return;
    }
    bodyEl.innerHTML = data.sections.map(s => `
      <div class="reading-section-card">
        <div class="reading-section-head">
          <h4>${escapeHtml(s.label)}</h4>
          <span class="reading-citation">${escapeHtml(s.citation)}</span>
        </div>
        <p class="reading-text">${s.text ? escapeHtml(s.text) : 'Text unavailable for this translation — see the official reading at USCCB.org.'}</p>
      </div>`).join('');
  } catch (e) {
    bodyEl.innerHTML = `<div class="empty-state">Couldn't load today's readings. Use the link below to read them at USCCB.org.</div>`;
  }
}

// ============================================================
// Daily Devotional
// ============================================================
async function loadDevotional() {
  const bodyEl = document.getElementById('devotionalBody');
  bodyEl.innerHTML = `<div class="empty-state">Loading today's devotional…</div>`;
  const today = new Date();
  const dateKeyStr = ymd(today);

  try {
    const { data: { session } } = await sb.auth.getSession();
    const res = await fetch('/.netlify/functions/daily-devotional', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${session?.access_token || ''}`
      },
      body: JSON.stringify({ date: dateKeyStr })
    });
    const data = await res.json();
    if (!res.ok) {
      if (res.status === 501 || data.code === 'NOT_CONFIGURED') {
        bodyEl.innerHTML = `<div class="empty-state">The devotional generator isn't set up yet — the group admin needs to add an Anthropic API key.</div>`;
        return;
      }
      throw new Error(data.error || 'Could not load devotional.');
    }
    bodyEl.innerHTML = `
      <div class="devo-card">
        <div class="devo-title">${escapeHtml(data.title)}</div>
        ${data.citation ? `<div class="guide-meta">${escapeHtml(data.citation)}</div>` : ''}
        ${data.scripture_text ? `<blockquote class="devo-scripture">${escapeHtml(data.scripture_text)}</blockquote>` : ''}
        <div class="guide-section"><h4>Reflection</h4><p>${escapeHtml(data.reflection).replace(/\n+/g, '</p><p>')}</p></div>
        <div class="guide-section"><h4>Today's Challenge</h4><p>${escapeHtml(data.challenge)}</p></div>
        <div class="guide-section"><h4>Closing Prayer</h4><p>${escapeHtml(data.closing_prayer)}</p></div>
      </div>`;
  } catch (e) {
    bodyEl.innerHTML = `<div class="empty-state">${escapeHtml(e.message || "Couldn't load today's devotional.")}</div>`;
  }
}

// ============================================================
// Study Guides
// ============================================================
document.getElementById('newGuideBtn').addEventListener('click', () => {
  document.getElementById('guideUploadPreview').classList.add('hidden');
  document.getElementById('guideGenerator').classList.toggle('hidden');
});
document.getElementById('cancelGuideBtn').addEventListener('click', () => {
  document.getElementById('guideGenerator').classList.add('hidden');
});

document.getElementById('generateGuideBtn').addEventListener('click', async () => {
  const topic = document.getElementById('guideTopic').value.trim();
  if (!topic) { toast('Give it a topic or passage first.', true); return; }
  if (!currentProfile) return;
  const notes = document.getElementById('guideNotes').value.trim();
  const useIdeas = document.getElementById('guideUseIdeas').checked;

  const statusEl = document.getElementById('guideGenStatus');
  statusEl.classList.remove('hidden', 'error');
  statusEl.textContent = 'Generating your study guide… this can take a moment.';
  document.getElementById('generateGuideBtn').disabled = true;

  try {
    let topIdeas = [];
    if (useIdeas) {
      const { data: ideas } = await sb.from('ideas').select('*').order('created_at', { ascending: false }).limit(50);
      if (ideas && ideas.length) {
        topIdeas = [...ideas].sort((a, b) => (b.voter_ids?.length || 0) - (a.voter_ids?.length || 0)).slice(0, 3).map(i => i.idea_text);
      }
    }

    const { data: { session } } = await sb.auth.getSession();
    const res = await fetch('/.netlify/functions/generate-guide', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${session?.access_token || ''}`
      },
      body: JSON.stringify({ topic, notes, topIdeas })
    });

    if (!res.ok) {
      const errBody = await res.json().catch(() => ({}));
      if (res.status === 501 || errBody.code === 'NOT_CONFIGURED') {
        throw new Error("The AI generator isn't set up yet on this site — the group admin needs to add an Anthropic API key. In the meantime you can write guides by hand.");
      }
      throw new Error(errBody.error || 'The generator hit a snag. Try again in a moment.');
    }

    const guide = await res.json();

    const { error } = await sb.from('study_guides').insert({
      title: guide.title || topic,
      scripture_ref: guide.scriptureRef || '',
      opening_prayer: guide.openingPrayer || '',
      context: guide.context || '',
      reflection_questions: guide.reflectionQuestions || [],
      discussion_questions: guide.discussionQuestions || [],
      application: guide.application || '',
      closing_prayer: guide.closingPrayer || '',
      created_by: currentProfile.display_name,
      created_by_id: currentProfile.id,
    });
    if (error) throw error;

    statusEl.classList.add('hidden');
    document.getElementById('guideGenerator').classList.add('hidden');
    document.getElementById('guideTopic').value = '';
    document.getElementById('guideNotes').value = '';
    toast('Study guide generated!');
    loadGuides();
  } catch (e) {
    statusEl.classList.remove('hidden');
    statusEl.classList.add('error');
    statusEl.textContent = e.message || 'Something went wrong generating the guide.';
  } finally {
    document.getElementById('generateGuideBtn').disabled = false;
  }
});

let allGuidesCache = [];
let allGuideCommentsCache = {};

async function loadGuides() {
  const listEl = document.getElementById('guideList');
  const { data, error } = await sb.from('study_guides').select('*').order('created_at', { ascending: false });
  if (error) { listEl.innerHTML = `<div class="empty-state">Couldn't load study guides.</div>`; return; }
  allGuidesCache = data || [];
  if (!allGuidesCache.length) {
    listEl.innerHTML = `<div class="empty-state">No study guides yet — generate your first one above.</div>`;
    updateHomeGuideCard(null);
    return;
  }
  updateHomeGuideCard(allGuidesCache[0]);

  const { data: comments } = await sb.from('guide_comments').select('*').order('created_at', { ascending: true });
  allGuideCommentsCache = {};
  (comments || []).forEach(c => { (allGuideCommentsCache[c.guide_id] ||= []).push(c); });

  renderGuideList();
}

function renderGuideList() {
  const listEl = document.getElementById('guideList');
  const query = (document.getElementById('guideSearchInput')?.value || '').trim().toLowerCase();
  const data = !query ? allGuidesCache : allGuidesCache.filter(g => {
    const haystack = [g.title, g.scripture_ref, g.series_week].filter(Boolean).join(' ').toLowerCase();
    return haystack.includes(query);
  });

  if (!data.length) {
    listEl.innerHTML = `<div class="empty-state">No guides match "${escapeHtml(query)}".</div>`;
    return;
  }

  listEl.innerHTML = data.map(g => guideCardHtml(g, allGuideCommentsCache[g.id] || [])).join('');
  listEl.querySelectorAll('.guide-head').forEach(head => {
    head.addEventListener('click', () => {
      head.nextElementSibling.classList.toggle('is-open');
    });
  });
  listEl.querySelectorAll('.guide-print-btn').forEach(btn => {
    btn.addEventListener('click', (e) => {
      e.stopPropagation();
      const guide = allGuidesCache.find(g => g.id === btn.dataset.guideId);
      if (guide) printGuide(guide);
    });
  });
  listEl.querySelectorAll('.guide-comment-form').forEach(form => {
    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      if (!currentProfile) return;
      const textarea = form.querySelector('textarea');
      const text = textarea.value.trim();
      if (!text) return;
      const { error } = await sb.from('guide_comments').insert({
        guide_id: form.dataset.guideId,
        comment_text: text,
        author: currentProfile.display_name,
        author_id: currentProfile.id,
      });
      if (error) { toast('Could not post comment.', true); return; }
      loadGuides();
    });
  });
}

document.getElementById('guideSearchInput').addEventListener('input', () => renderGuideList());

function formatGuideText(text) {
  if (!text) return '';
  const paragraphs = text.split(/\n{2,}/);
  return paragraphs.map(para => {
    const lines = para.split('\n').map(l => l.trim()).filter(l => l.length);
    if (!lines.length) return '';

    if (/^Leader tip:/i.test(lines[0])) {
      return `<div class="leader-tip">${lines.map(escapeHtml).join('<br>')}</div>`;
    }

    const numberedCount = lines.filter(l => /^\d+\.\s/.test(l)).length;
    if (numberedCount > 1 && numberedCount >= Math.ceil(lines.length * 0.6)) {
      const items = [];
      lines.forEach(l => {
        if (/^\d+\.\s/.test(l)) {
          items.push(l.replace(/^\d+\.\s/, ''));
        } else if (items.length) {
          items[items.length - 1] += ' ' + l;
        } else {
          items.push(l);
        }
      });
      return `<ol>${items.map(i => `<li>${escapeHtml(i)}</li>`).join('')}</ol>`;
    }

    return `<p>${lines.map(escapeHtml).join('<br>')}</p>`;
  }).join('');
}

function guideCardHtml(g, comments) {
  comments = comments || [];
  const reflect = Array.isArray(g.reflection_questions) ? g.reflection_questions : [];
  const discuss = Array.isArray(g.discussion_questions) ? g.discussion_questions : [];
  const sections = Array.isArray(g.sections) ? g.sections : [];
  const date = new Date(g.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
  const seriesBadge = g.series_week ? `<span class="guide-badge">${escapeHtml(g.series_week)}</span> · ` : '';

  let bodyHtml;
  if (sections.length) {
    // Richer imported guides: sections carry real HTML (bold/italic/lists/quotes preserved from the source doc).
    bodyHtml = sections.map(s => `
      <div class="guide-section">
        <h4>${escapeHtml(s.heading || '')}</h4>
        ${s.body || ''}
      </div>
    `).join('');
  } else {
    // Older AI-generated guide format (6 fixed fields).
    bodyHtml = `
      ${g.context ? `<div class="guide-section"><h4>Context</h4><p>${escapeHtml(g.context)}</p></div>` : ''}
      ${g.opening_prayer ? `<div class="guide-section"><h4>Opening Prayer</h4><p>${escapeHtml(g.opening_prayer)}</p></div>` : ''}
      ${reflect.length ? `<div class="guide-section"><h4>Reflection Questions</h4><ol>${reflect.map(q => `<li>${escapeHtml(q)}</li>`).join('')}</ol></div>` : ''}
      ${discuss.length ? `<div class="guide-section"><h4>Discussion Questions</h4><ol>${discuss.map(q => `<li>${escapeHtml(q)}</li>`).join('')}</ol></div>` : ''}
      ${g.application ? `<div class="guide-section"><h4>Living It Out</h4><p>${escapeHtml(g.application)}</p></div>` : ''}
      ${g.closing_prayer ? `<div class="guide-section"><h4>Closing Prayer</h4><p>${escapeHtml(g.closing_prayer)}</p></div>` : ''}
    `;
  }

  return `
  <div class="guide-card" data-guide-id="${g.id}">
    <div class="guide-head">
      <div>
        <div class="guide-title">${escapeHtml(g.title)}</div>
        <div class="guide-meta">${seriesBadge}${g.scripture_ref ? escapeHtml(g.scripture_ref) + ' · ' : ''}by ${escapeHtml(g.created_by)} · ${date}</div>
      </div>
      <button class="btn btn-ghost btn-sm">Open</button>
    </div>
    <div class="guide-body">
      ${bodyHtml}
      <div class="guide-actions">
        <button class="btn btn-ghost btn-sm guide-print-btn" data-guide-id="${g.id}">Print / Save as PDF</button>
      </div>
      <div class="guide-comments">
        <h4>Discussion / Takeaways</h4>
        ${comments.length ? comments.map(c => `
          <div class="guide-comment">
            <div class="guide-comment-author">${escapeHtml(c.author)}</div>
            <div class="guide-comment-text">${escapeHtml(c.comment_text)}</div>
          </div>`).join('') : `<div class="guide-comment-empty">No comments yet.</div>`}
        <form class="guide-comment-form" data-guide-id="${g.id}">
          <textarea rows="2" placeholder="Share a takeaway from this one…"></textarea>
          <button class="btn btn-primary btn-sm" type="submit">Post</button>
        </form>
      </div>
    </div>
  </div>`;
}

function printGuide(g) {
  const sections = Array.isArray(g.sections) ? g.sections : [];
  let sectionsHtml;
  if (sections.length) {
    sectionsHtml = sections.map(s => `
      <div class="print-section">
        <h3>${escapeHtml(s.heading || '')}</h3>
        ${s.body || ''}
      </div>
    `).join('');
  } else {
    const reflect = Array.isArray(g.reflection_questions) ? g.reflection_questions : [];
    const discuss = Array.isArray(g.discussion_questions) ? g.discussion_questions : [];
    sectionsHtml = `
      ${g.context ? `<div class="print-section"><h3>Context</h3><p>${escapeHtml(g.context)}</p></div>` : ''}
      ${g.opening_prayer ? `<div class="print-section"><h3>Opening Prayer</h3><p>${escapeHtml(g.opening_prayer)}</p></div>` : ''}
      ${reflect.length ? `<div class="print-section"><h3>Reflection Questions</h3><ol>${reflect.map(q => `<li>${escapeHtml(q)}</li>`).join('')}</ol></div>` : ''}
      ${discuss.length ? `<div class="print-section"><h3>Discussion Questions</h3><ol>${discuss.map(q => `<li>${escapeHtml(q)}</li>`).join('')}</ol></div>` : ''}
      ${g.application ? `<div class="print-section"><h3>Living It Out</h3><p>${escapeHtml(g.application)}</p></div>` : ''}
      ${g.closing_prayer ? `<div class="print-section"><h3>Closing Prayer</h3><p>${escapeHtml(g.closing_prayer)}</p></div>` : ''}
    `;
  }

  const win = window.open('', '_blank');
  win.document.write(`<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>${escapeHtml(g.title)}</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; max-width: 720px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 26px; margin-bottom: 4px; }
  .meta { font-family: monospace; font-size: 12px; color: #666; margin-bottom: 28px; }
  h3 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.06em; color: #8a6d1f; margin: 22px 0 6px; }
  p { font-size: 14.5px; margin: 0 0 10px; }
  ol, ul { font-size: 14.5px; padding-left: 22px; margin: 0 0 10px; }
  li { margin-bottom: 6px; }
  li p { margin: 0; }
  em { font-style: italic; }
  strong { font-weight: 700; }
  blockquote { margin: 10px 0; padding: 4px 16px; border-left: 3px solid #c9a227; color: #444; }
  blockquote p { margin: 0 0 4px; }
  .leader-tip { font-style: italic; color: #555; border-left: 3px solid #c9a227; padding: 6px 12px; margin: 10px 0; background: #faf6ea; }
  @media print { body { margin: 0; padding: 24px; } }
</style>
</head>
<body>
  <h1>${escapeHtml(g.title)}</h1>
  <div class="meta">${g.series_week ? escapeHtml(g.series_week) + ' · ' : ''}${g.scripture_ref ? escapeHtml(g.scripture_ref) : ''}</div>
  ${sectionsHtml}
</body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 300);
}

// ============================================================
// Upload a study guide from .docx
// ============================================================
let pendingParsedGuide = null;

document.getElementById('uploadGuideBtn').addEventListener('click', () => {
  document.getElementById('uploadGuideInput').click();
});

document.getElementById('uploadGuideInput').addEventListener('change', async (e) => {
  const file = e.target.files[0];
  e.target.value = ''; // allow re-selecting the same file later
  if (!file) return;

  try {
    const arrayBuffer = await file.arrayBuffer();
    const result = await window.mammoth.convertToHtml({ arrayBuffer });
    const parsed = parseGuideHtml(result.value);
    pendingParsedGuide = parsed;

    document.getElementById('uploadTitle').value = parsed.title;
    document.getElementById('uploadScriptureRef').value = parsed.scriptureRef;
    document.getElementById('uploadSeriesWeek').value = '';

    const previewEl = document.getElementById('uploadSectionsPreview');
    if (parsed.sections.length) {
      previewEl.innerHTML = `<div class="upload-sections-count">${parsed.sections.length} sections detected</div>
        <ul>${parsed.sections.map(s => `<li>${escapeHtml(s.heading)}</li>`).join('')}</ul>`;
    } else {
      previewEl.innerHTML = `<div class="upload-sections-count">No section headings detected — the whole document will be saved as one section. You can still save and edit later if needed.</div>`;
    }

    document.getElementById('guideGenerator').classList.add('hidden');
    document.getElementById('guideUploadPreview').classList.remove('hidden');
    document.getElementById('guideUploadStatus').classList.add('hidden');
  } catch (err) {
    toast("Couldn't read that file — make sure it's a .docx.", true);
  }
});

document.getElementById('cancelUploadGuideBtn').addEventListener('click', () => {
  pendingParsedGuide = null;
  document.getElementById('guideUploadPreview').classList.add('hidden');
});

document.getElementById('saveUploadedGuideBtn').addEventListener('click', async () => {
  if (!pendingParsedGuide || !currentProfile) return;
  const statusEl = document.getElementById('guideUploadStatus');
  const btn = document.getElementById('saveUploadedGuideBtn');
  btn.disabled = true;
  statusEl.classList.add('hidden', 'error');

  const title = document.getElementById('uploadTitle').value.trim();
  if (!title) {
    statusEl.textContent = 'Give the guide a title first.';
    statusEl.classList.remove('hidden');
    statusEl.classList.add('error');
    btn.disabled = false;
    return;
  }

  try {
    const { error } = await sb.from('study_guides').insert({
      title,
      scripture_ref: document.getElementById('uploadScriptureRef').value.trim(),
      series_week: document.getElementById('uploadSeriesWeek').value.trim(),
      context: '',
      reflection_questions: [],
      discussion_questions: [],
      sections: pendingParsedGuide.sections,
      created_by: currentProfile.display_name,
      created_by_id: currentProfile.id,
    });
    if (error) throw error;

    pendingParsedGuide = null;
    document.getElementById('guideUploadPreview').classList.add('hidden');
    toast('Study guide uploaded!');
    loadGuides();
  } catch (err) {
    statusEl.textContent = err.message || 'Could not save the guide. Try again.';
    statusEl.classList.remove('hidden');
    statusEl.classList.add('error');
  } finally {
    btn.disabled = false;
  }
});

// Parses mammoth's HTML output into { title, scriptureRef, sections }, keeping real
// bold/italic/list/quote formatting from the source doc intact (not flattened to plain text).
// Heuristic mirrors the format used across this group's existing guides:
// two bold lines at the top (a label, then the real title), a "Passage:" line,
// then the body split into sections wherever a short fully-bold-only line appears.
const GUIDE_ALLOWED_TAGS = new Set(['P', 'STRONG', 'EM', 'BLOCKQUOTE', 'UL', 'OL', 'LI', 'BR']);

function sanitizeGuideEl(el) {
  el.querySelectorAll('*').forEach(node => {
    while (node.attributes.length) node.removeAttribute(node.attributes[0].name);
    if (!GUIDE_ALLOWED_TAGS.has(node.tagName)) {
      // unwrap: replace node with its children
      const parent = node.parentNode;
      while (node.firstChild) parent.insertBefore(node.firstChild, node);
      parent.removeChild(node);
    }
  });
  return el;
}

function parseGuideHtml(html) {
  const container = document.createElement('div');
  container.innerHTML = html;
  const blocks = Array.from(container.children).filter(el => /^(P|BLOCKQUOTE|UL|OL|H1|H2|H3|H4)$/.test(el.tagName));

  function textOf(el) { return el.textContent.replace(/\s+/g, ' ').trim(); }
  function isHeading(el) {
    if (el.tagName !== 'P') return false;
    if (el.querySelector('em')) return false;
    const strongs = el.querySelectorAll('strong');
    if (!strongs.length) return false;
    let strongText = '';
    strongs.forEach(s => strongText += s.textContent);
    const text = textOf(el);
    return strongText.replace(/\s+/g, ' ').trim() === text && text.length > 0 && text.length <= 70;
  }

  let header = null, title = null, scriptureRef = '';
  let boldCount = 0;
  const consumed = new Set();
  let bodyStart = 0;

  for (let i = 0; i < blocks.length; i++) {
    if (blocks[i].tagName !== 'P') { bodyStart = i; break; }
    const text = textOf(blocks[i]);
    if (!text) { consumed.add(i); continue; }

    const passageMatch = text.match(/^Passage:?\s*(.+)$/i);
    if (passageMatch) {
      scriptureRef = passageMatch[1].replace(/\s*[·|].*$/, '').trim();
      consumed.add(i);
      continue;
    }
    if (isHeading(blocks[i]) && boldCount < 2) {
      if (boldCount === 0) header = text; else title = text;
      boldCount++;
      consumed.add(i);
      continue;
    }
    if (boldCount >= 1) { bodyStart = i; break; }
    bodyStart = i + 1;
  }
  if (!title) title = header || 'Untitled Guide';

  const sections = [];
  let currentHeading = null;
  let currentParts = [];

  function pushSection() {
    if (currentHeading === null && !currentParts.length) return;
    const bodyHtml = currentParts.map(el => sanitizeGuideEl(el).outerHTML).join('').trim();
    if (bodyHtml || currentHeading) sections.push({ heading: currentHeading || 'Intro', body: bodyHtml });
  }

  for (let i = bodyStart; i < blocks.length; i++) {
    if (consumed.has(i)) continue;
    const el = blocks[i];
    if (isHeading(el)) {
      pushSection();
      currentHeading = textOf(el);
      currentParts = [];
    } else {
      currentParts.push(el);
    }
  }
  pushSection();

  const filtered = sections.filter(s => !(s.heading === 'Intro' && s.body.length < 20));
  return { title, scriptureRef, sections: filtered };
}

// ============================================================
// Ideas
// ============================================================
document.getElementById('addIdeaBtn').addEventListener('click', async () => {
  const text = document.getElementById('ideaText').value.trim();
  if (!text) { toast('Write your idea first.', true); return; }
  if (!currentProfile) return;
  const { error } = await sb.from('ideas').insert({
    idea_text: text,
    author: currentProfile.display_name,
    author_id: currentProfile.id,
    voter_ids: []
  });
  if (error) { toast('Could not add idea.', true); return; }
  document.getElementById('ideaText').value = '';
  toast('Idea added!');
  loadIdeas();
});

async function loadIdeas() {
  const listEl = document.getElementById('ideaList');
  const { data, error } = await sb.from('ideas').select('*').order('created_at', { ascending: false });
  if (error) { listEl.innerHTML = `<div class="empty-state">Couldn't load ideas.</div>`; return; }
  if (!data || !data.length) {
    listEl.innerHTML = `<div class="empty-state">No ideas yet — be the first to suggest a topic.</div>`;
    updateHomeIdeaCard(null);
    return;
  }
  const sorted = [...data].sort((a, b) => (b.voter_ids?.length || 0) - (a.voter_ids?.length || 0));
  updateHomeIdeaCard(sorted[0]);
  const myId = currentProfile?.id;
  listEl.innerHTML = sorted.map(i => {
    const voters = i.voter_ids || [];
    const voted = myId && voters.includes(myId);
    return `
    <div class="idea-card" data-id="${i.id}">
      <button class="vote-btn ${voted ? 'voted' : ''}" data-vote="${i.id}">
        <span>${voters.length}</span>
        <span class="vote-count-label">votes</span>
      </button>
      <div>
        <div class="idea-text">${escapeHtml(i.idea_text)}</div>
        <div class="idea-author">— ${escapeHtml(i.author)}</div>
      </div>
    </div>`;
  }).join('');
  listEl.querySelectorAll('[data-vote]').forEach(btn => {
    btn.addEventListener('click', () => toggleVote(btn.dataset.vote));
  });
}

async function toggleVote(ideaId) {
  if (!currentProfile) return;
  const { data, error } = await sb.from('ideas').select('voter_ids').eq('id', ideaId).single();
  if (error) { toast('Could not update vote.', true); return; }
  let voters = data.voter_ids || [];
  if (voters.includes(currentProfile.id)) voters = voters.filter(v => v !== currentProfile.id);
  else voters = [...voters, currentProfile.id];
  const { error: updErr } = await sb.from('ideas').update({ voter_ids: voters }).eq('id', ideaId);
  if (updErr) { toast('Could not update vote.', true); return; }
  loadIdeas();
}

// ============================================================
// Prayer Requests
// ============================================================
let prayerFilter = 'open';
document.getElementById('addPrayerBtn').addEventListener('click', async () => {
  const text = document.getElementById('prayerText').value.trim();
  if (!text) { toast('Write the request first.', true); return; }
  if (!currentProfile) return;
  const { error } = await sb.from('prayer_requests').insert({
    request_text: text,
    author: currentProfile.display_name,
    author_id: currentProfile.id,
  });
  if (error) { toast('Could not post request.', true); return; }
  document.getElementById('prayerText').value = '';
  toast('Prayer request posted.');
  loadPrayerRequests();
});

document.querySelectorAll('[data-prayer-filter]').forEach(btn => {
  btn.addEventListener('click', () => {
    prayerFilter = btn.dataset.prayerFilter;
    document.querySelectorAll('[data-prayer-filter]').forEach(b => b.classList.toggle('is-active', b === btn));
    loadPrayerRequests();
  });
});

async function loadPrayerRequests() {
  const listEl = document.getElementById('prayerList');
  const { data, error } = await sb.from('prayer_requests').select('*').order('created_at', { ascending: false });
  if (error) { listEl.innerHTML = `<div class="empty-state">Couldn't load prayer requests.</div>`; return; }
  if (!data || !data.length) {
    listEl.innerHTML = `<div class="empty-state">No prayer requests yet.</div>`;
    return;
  }
  const filtered = data.filter(p => {
    if (prayerFilter === 'open') return !p.is_answered;
    if (prayerFilter === 'answered') return p.is_answered;
    return true;
  });
  if (!filtered.length) {
    listEl.innerHTML = `<div class="empty-state">Nothing here right now.</div>`;
    return;
  }
  const myId = currentProfile?.id;
  listEl.innerHTML = filtered.map(p => {
    const praying = p.praying_ids || [];
    const isPraying = myId && praying.includes(myId);
    const date = new Date(p.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
    return `
    <div class="prayer-card ${p.is_answered ? 'is-answered' : ''}">
      <div class="prayer-text">${escapeHtml(p.request_text)}</div>
      <div class="prayer-meta">— ${escapeHtml(p.author)} · ${date}${p.is_answered ? ' · <span class="prayer-answered-tag">Answered</span>' : ''}</div>
      ${p.is_answered && p.answered_note ? `<div class="prayer-answered-note">${escapeHtml(p.answered_note)}</div>` : ''}
      <div class="prayer-actions">
        <button class="btn btn-ghost btn-sm ${isPraying ? 'is-active' : ''}" data-pray="${p.id}">🙏 Praying (${praying.length})</button>
        ${!p.is_answered ? `<button class="btn btn-ghost btn-sm" data-mark-answered="${p.id}">Mark answered</button>` : `<button class="btn btn-ghost btn-sm" data-mark-open="${p.id}">Reopen</button>`}
      </div>
    </div>`;
  }).join('');

  listEl.querySelectorAll('[data-pray]').forEach(btn => {
    btn.addEventListener('click', () => togglePraying(btn.dataset.pray));
  });
  listEl.querySelectorAll('[data-mark-answered]').forEach(btn => {
    btn.addEventListener('click', () => markPrayerAnswered(btn.dataset.markAnswered));
  });
  listEl.querySelectorAll('[data-mark-open]').forEach(btn => {
    btn.addEventListener('click', async () => {
      await sb.from('prayer_requests').update({ is_answered: false, answered_note: null }).eq('id', btn.dataset.markOpen);
      loadPrayerRequests();
    });
  });
}

async function togglePraying(id) {
  if (!currentProfile) return;
  const { data, error } = await sb.from('prayer_requests').select('praying_ids').eq('id', id).single();
  if (error) { toast('Could not update.', true); return; }
  let ids = data.praying_ids || [];
  if (ids.includes(currentProfile.id)) ids = ids.filter(v => v !== currentProfile.id);
  else ids = [...ids, currentProfile.id];
  const { error: updErr } = await sb.from('prayer_requests').update({ praying_ids: ids }).eq('id', id);
  if (updErr) { toast('Could not update.', true); return; }
  loadPrayerRequests();
}

async function markPrayerAnswered(id) {
  const note = prompt('Optional: how was this answered? (leave blank to skip)');
  const { error } = await sb.from('prayer_requests').update({ is_answered: true, answered_note: note || null }).eq('id', id);
  if (error) { toast('Could not update.', true); return; }
  toast('Marked as answered.');
  loadPrayerRequests();
}

// ============================================================
// Homework
// ============================================================
document.getElementById('newHomeworkBtn').addEventListener('click', () => {
  document.getElementById('homeworkComposer').classList.toggle('hidden');
});
document.getElementById('cancelHomeworkBtn').addEventListener('click', () => {
  document.getElementById('homeworkComposer').classList.add('hidden');
});
document.getElementById('saveHomeworkBtn').addEventListener('click', async () => {
  const title = document.getElementById('hwTitle').value.trim();
  const questionsRaw = document.getElementById('hwQuestions').value.trim();
  const dueDate = document.getElementById('hwDueDate').value || null;
  if (!title || !questionsRaw) { toast('Add a title and at least one question.', true); return; }
  if (!currentProfile) return;
  const questions = questionsRaw.split('\n').map(q => q.trim()).filter(Boolean)
    .map(text => ({ text, category: null, assignedTo: '' }));

  const { error } = await sb.from('homework_sessions').insert({
    title, questions, due_date: dueDate,
    created_by: currentProfile.display_name,
    created_by_id: currentProfile.id
  });
  if (error) { toast('Could not post session.', true); return; }
  document.getElementById('hwTitle').value = '';
  document.getElementById('hwQuestions').value = '';
  document.getElementById('hwDueDate').value = '';
  document.getElementById('homeworkComposer').classList.add('hidden');
  toast('Homework posted!');
  loadHomework();
});

let loadedHomeworkSessions = [];

function normalizeHwQuestion(q) {
  if (typeof q === 'string') return { text: q, category: null, assignedTo: '' };
  return { text: q.text || '', category: q.category || null, assignedTo: q.assignedTo || '' };
}

async function loadHomework() {
  const listEl = document.getElementById('homeworkList');
  const { data: sessions, error } = await sb.from('homework_sessions').select('*').order('created_at', { ascending: false });
  if (error) { listEl.innerHTML = `<div class="empty-state">Couldn't load homework.</div>`; return; }
  loadedHomeworkSessions = sessions || [];
  if (!sessions || !sessions.length) {
    listEl.innerHTML = `<div class="empty-state">No homework posted yet.</div>`;
    updateHomeHomeworkCard(null, []);
    return;
  }
  const { data: answers } = await sb.from('homework_answers').select('*').order('created_at', { ascending: true });
  const answersBySession = {};
  (answers || []).forEach(a => {
    (answersBySession[a.session_id] ||= []).push(a);
  });

  updateHomeHomeworkCard(sessions[0], answersBySession[sessions[0].id] || []);

  listEl.innerHTML = sessions.map(s => homeworkCardHtml(s, answersBySession[s.id] || [])).join('');

  listEl.querySelectorAll('.hw-answer-form').forEach(form => {
    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      if (!currentProfile) return;
      const sessionId = form.dataset.session;
      const qIndex = Number(form.dataset.qindex);
      const textarea = form.querySelector('textarea');
      const text = textarea.value.trim();
      if (!text) return;
      const { error } = await sb.from('homework_answers').insert({
        session_id: sessionId, question_index: qIndex,
        author: currentProfile.display_name, author_id: currentProfile.id,
        answer: text
      });
      if (error) { toast('Could not submit answer.', true); return; }
      toast('Answer submitted!');
      loadHomework();
    });
  });

  listEl.querySelectorAll('.hw-assign-input').forEach(input => {
    input.addEventListener('change', async () => {
      const sessionId = input.dataset.session;
      const qIdx = Number(input.dataset.qindex);
      const session = loadedHomeworkSessions.find(s => s.id === sessionId);
      if (!session) return;
      const questions = (Array.isArray(session.questions) ? session.questions : []).map(normalizeHwQuestion);
      questions[qIdx] = { ...questions[qIdx], assignedTo: input.value.trim() };
      const { error } = await sb.from('homework_sessions').update({ questions }).eq('id', sessionId);
      if (error) { toast('Could not save assignment.', true); return; }
      session.questions = questions;
      toast('Assignment saved.');
      loadHomework();
    });
  });
}
function homeworkCardHtml(s, answers) {
  const due = s.due_date ? new Date(s.due_date + 'T00:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : null;
  const questions = Array.isArray(s.questions) ? s.questions : [];

  const assignedIdx = [];
  const unassignedIdx = [];
  questions.forEach((qRaw, idx) => {
    const q = normalizeHwQuestion(qRaw);
    (q.assignedTo ? assignedIdx : unassignedIdx).push(idx);
  });

  function fullQuestionCard(idx) {
    const q = normalizeHwQuestion(questions[idx]);
    const qAnswers = answers.filter(a => a.question_index === idx);
    return `
      <div class="hw-question">
        <div class="hw-question-head">
          <div class="hw-question-text">${idx + 1}. ${escapeHtml(q.text)}</div>
          ${q.category ? `<span class="hw-category">${escapeHtml(q.category)}</span>` : ''}
        </div>
        <label class="hw-assign-row">Assigned to
          <input type="text" class="hw-assign-input" data-session="${s.id}" data-qindex="${idx}" value="${escapeHtml(q.assignedTo)}" placeholder="Name">
        </label>
        <div class="hw-answers">
          ${qAnswers.length ? qAnswers.map(a => `
            <div class="hw-answer">
              <div class="hw-answer-author">${escapeHtml(a.author)}</div>
              ${escapeHtml(a.answer)}
            </div>`).join('') : `<div class="hw-answer" style="opacity:0.6">No answers yet.</div>`}
        </div>
        <form class="hw-answer-form" data-session="${s.id}" data-qindex="${idx}">
          <textarea rows="2" placeholder="Your 3–5 minute synopsis…"></textarea>
          <button class="btn btn-primary btn-sm" type="submit">Post</button>
        </form>
      </div>`;
  }

  function compactRow(idx) {
    const q = normalizeHwQuestion(questions[idx]);
    return `
      <div class="hw-compact-row">
        <div class="hw-compact-text">${idx + 1}. ${escapeHtml(q.text)}</div>
        <input type="text" class="hw-assign-input hw-assign-input-compact" data-session="${s.id}" data-qindex="${idx}" value="" placeholder="Assign to…">
      </div>`;
  }

  // Group the unassigned pool by category for easier browsing.
  const unassignedByCategory = {};
  unassignedIdx.forEach(idx => {
    const cat = normalizeHwQuestion(questions[idx]).category || 'Other';
    (unassignedByCategory[cat] ||= []).push(idx);
  });

  return `
  <div class="hw-card">
    <div class="hw-head">
      <div>
        <div class="hw-title">${escapeHtml(s.title)}</div>
        <div class="hw-due">Posted by ${escapeHtml(s.created_by)}${due ? ' · due ' + due : ''} · ${assignedIdx.length} of ${questions.length} assigned</div>
      </div>
    </div>

    ${assignedIdx.length ? assignedIdx.map(fullQuestionCard).join('') : `<div class="empty-state" style="margin-top:16px;">No one's picked a question yet — assign one from the list below.</div>`}

    ${unassignedIdx.length ? `
      <details class="hw-unassigned">
        <summary>Unassigned questions (${unassignedIdx.length}) — browse &amp; assign</summary>
        <div class="hw-unassigned-body">
          ${Object.entries(unassignedByCategory).map(([cat, idxs]) => `
            <div class="hw-category-group">
              <div class="hw-category-group-title">${escapeHtml(cat)}</div>
              ${idxs.map(compactRow).join('')}
            </div>
          `).join('')}
        </div>
      </details>
    ` : ''}
  </div>`;
}

// ============================================================
// Calendar
// ============================================================
let calViewDate = new Date();
document.getElementById('calPrev').addEventListener('click', () => { calViewDate.setMonth(calViewDate.getMonth() - 1); renderCalendar(); });
document.getElementById('calNext').addEventListener('click', () => { calViewDate.setMonth(calViewDate.getMonth() + 1); renderCalendar(); });

document.getElementById('newEventBtn').addEventListener('click', () => {
  document.getElementById('eventComposer').classList.toggle('hidden');
});
document.getElementById('cancelEventBtn').addEventListener('click', () => {
  document.getElementById('eventComposer').classList.add('hidden');
});
document.getElementById('evRepeats').addEventListener('change', (e) => {
  document.getElementById('evRepeatUntilRow').classList.toggle('hidden', !e.target.checked);
});
document.getElementById('saveEventBtn').addEventListener('click', async () => {
  const title = document.getElementById('evTitle').value.trim();
  const date = document.getElementById('evDate').value;
  const time = document.getElementById('evTime').value || null;
  const location = document.getElementById('evLocation').value.trim();
  const note = document.getElementById('evNote').value.trim();
  const isMeeting = document.getElementById('evIsMeeting').checked;
  const repeats = document.getElementById('evRepeats').checked;
  const repeatUntil = document.getElementById('evRepeatUntil').value;
  if (!title || !date) { toast('Add a title and date.', true); return; }
  if (repeats && !repeatUntil) { toast('Pick a "repeat until" date.', true); return; }
  if (!currentProfile) return;

  const dates = [date];
  if (repeats) {
    let d = new Date(date + 'T00:00:00');
    const end = new Date(repeatUntil + 'T00:00:00');
    while (true) {
      d = new Date(d.getTime() + 7 * 24 * 60 * 60 * 1000);
      if (d > end) break;
      dates.push(ymd(d));
    }
  }

  const rows = dates.map(event_date => ({
    title, event_date, event_time: time, location, note, is_meeting: isMeeting,
    added_by: currentProfile.display_name, added_by_id: currentProfile.id
  }));
  const { error } = await sb.from('calendar_events').insert(rows);
  if (error) { toast('Could not add event.', true); return; }
  document.getElementById('evTitle').value = '';
  document.getElementById('evDate').value = '';
  document.getElementById('evTime').value = '';
  document.getElementById('evLocation').value = '';
  document.getElementById('evNote').value = '';
  document.getElementById('evIsMeeting').checked = false;
  document.getElementById('evRepeats').checked = false;
  document.getElementById('evRepeatUntil').value = '';
  document.getElementById('evRepeatUntilRow').classList.add('hidden');
  document.getElementById('eventComposer').classList.add('hidden');
  toast(rows.length > 1 ? `${rows.length} events added!` : 'Event added!');
  loadCalendarEvents();
});

let groupEventsCache = [];
async function loadCalendarEvents() {
  const { data, error } = await sb.from('calendar_events').select('*').order('event_date', { ascending: true });
  if (!error) groupEventsCache = data || [];
  renderCalendar();
  updateHomeMeetingCard();
}

async function deleteEvent(id) {
  const { error } = await sb.from('calendar_events').delete().eq('id', id);
  if (error) { toast('Could not delete event.', true); return; }
  toast('Event removed.');
  loadCalendarEvents();
  document.getElementById('calDayDetail').classList.add('hidden');
}

function renderCalendar() {
  const year = calViewDate.getFullYear();
  const month = calViewDate.getMonth();
  document.getElementById('calMonthLabel').textContent = calViewDate.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });

  const grid = document.getElementById('calGrid');
  grid.innerHTML = '';
  ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(d => {
    const el = document.createElement('div');
    el.className = 'cal-dow';
    el.textContent = d;
    grid.appendChild(el);
  });

  const firstDay = new Date(year, month, 1);
  const startOffset = firstDay.getDay();
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const todayKey = ymd(new Date());

  const feasts = [...feastsForYear(year), ...feastsForYear(year - 1), ...feastsForYear(year + 1)];

  for (let i = 0; i < startOffset; i++) {
    const el = document.createElement('div');
    el.className = 'cal-day is-empty';
    grid.appendChild(el);
  }

  for (let day = 1; day <= daysInMonth; day++) {
    const key = dateKey(year, month + 1, day);
    const dayFeasts = feasts.filter(f => ymd(f.date) === key);
    const dayEvents = groupEventsCache.filter(e => e.event_date === key);

    const el = document.createElement('div');
    el.className = 'cal-day' + (key === todayKey ? ' is-today' : '');
    el.innerHTML = `
      <div class="cal-day-num">${day}</div>
      <div class="cal-dot-row">
        ${dayFeasts.map(f => `<span class="dot ${f.holyDay ? 'dot-holyday' : 'dot-feast'}"></span>`).join('')}
        ${dayEvents.map(e => `<span class="dot ${e.is_meeting ? 'dot-meeting' : 'dot-event'}"></span>`).join('')}
      </div>`;
    el.addEventListener('click', () => showDayDetail(key, dayFeasts, dayEvents));
    grid.appendChild(el);
  }
}

function showDayDetail(key, feasts, events) {
  const detail = document.getElementById('calDayDetail');
  if (!feasts.length && !events.length) { detail.classList.add('hidden'); return; }
  const dateObj = new Date(key + 'T00:00:00');
  const label = dateObj.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' });
  const myId = currentProfile?.id;
  detail.classList.remove('hidden');
  detail.innerHTML = `<h3 style="margin-bottom:10px;">${label}</h3>` +
    feasts.map(f => `<div class="cal-detail-item"><span class="cal-detail-tag" style="background:${f.holyDay ? '#8c2a2a1a' : '#a8823c1a'};color:${f.holyDay ? '#8c2a2a' : '#a8823c'}">${f.holyDay ? 'Holy Day' : 'Feast'}</span>${escapeHtml(f.name)}</div>`).join('') +
    events.map(e => {
      const when = [
        e.event_time ? formatTime(e.event_time) : null,
        e.location ? escapeHtml(e.location) : null
      ].filter(Boolean).join(' · ');
      const attendees = Array.isArray(e.attendees) ? e.attendees : [];
      const attendanceHtml = e.is_meeting ? `
        <div class="cal-attendance">
          <div class="cal-attendance-label">Attendance (${attendees.length})</div>
          <div class="cal-attendee-chips">
            ${attendees.map(name => `<span class="cal-attendee-chip">${escapeHtml(name)} <button data-remove-attendee="${e.id}" data-name="${escapeHtml(name)}">×</button></span>`).join('') || '<span class="cal-attendee-empty">No one checked in yet.</span>'}
          </div>
          <form class="cal-add-attendee-form" data-event="${e.id}">
            <input type="text" placeholder="Add name…" class="cal-add-attendee-input">
            <button class="btn btn-ghost btn-sm" type="submit">Add</button>
          </form>
        </div>` : '';
      return `<div class="cal-detail-item"><span class="cal-detail-tag" style="background:${e.is_meeting ? '#3f6e4e1a' : '#9a8f7e1a'};color:${e.is_meeting ? '#3f6e4e' : '#6b5f52'}">${e.is_meeting ? 'Meeting' : 'Event'}</span>${escapeHtml(e.title)}${when ? ` <span class="cal-detail-when">(${when})</span>` : ''}${e.note ? ' — ' + escapeHtml(e.note) : ''} <span style="color:var(--ink-faint)">(${escapeHtml(e.added_by)})</span>${myId && e.added_by_id === myId ? `<button class="cal-detail-delete" data-del="${e.id}">remove</button>` : ''}${attendanceHtml}</div>`;
    }).join('');
  detail.querySelectorAll('[data-del]').forEach(btn => {
    btn.addEventListener('click', () => deleteEvent(btn.dataset.del));
  });
  detail.querySelectorAll('.cal-add-attendee-form').forEach(form => {
    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      const input = form.querySelector('input');
      const name = input.value.trim();
      if (!name) return;
      await addAttendee(form.dataset.event, name);
    });
  });
  detail.querySelectorAll('[data-remove-attendee]').forEach(btn => {
    btn.addEventListener('click', () => removeAttendee(btn.dataset.removeAttendee, btn.dataset.name));
  });
}

async function addAttendee(eventId, name) {
  const ev = groupEventsCache.find(e => e.id === eventId);
  if (!ev) return;
  const attendees = Array.isArray(ev.attendees) ? ev.attendees : [];
  if (attendees.includes(name)) return;
  const updated = [...attendees, name];
  const { error } = await sb.from('calendar_events').update({ attendees: updated }).eq('id', eventId);
  if (error) { toast('Could not update attendance.', true); return; }
  ev.attendees = updated;
  loadCalendarEvents();
  const key = ev.event_date;
  showDayDetail(key, [], groupEventsCache.filter(e => e.event_date === key));
}

async function removeAttendee(eventId, name) {
  const ev = groupEventsCache.find(e => e.id === eventId);
  if (!ev) return;
  const attendees = (Array.isArray(ev.attendees) ? ev.attendees : []).filter(n => n !== name);
  const { error } = await sb.from('calendar_events').update({ attendees }).eq('id', eventId);
  if (error) { toast('Could not update attendance.', true); return; }
  ev.attendees = attendees;
  loadCalendarEvents();
  const key = ev.event_date;
  showDayDetail(key, [], groupEventsCache.filter(e => e.event_date === key));
}

// ============================================================
// Home dashboard cards
// ============================================================
function updateHomeGuideCard(g) {
  const el = document.getElementById('recentGuideBody');
  el.textContent = g ? `${g.title}${g.scripture_ref ? ' · ' + g.scripture_ref : ''}` : 'No guides yet.';
}
function updateHomeIdeaCard(i) {
  const el = document.getElementById('topIdeaBody');
  el.textContent = i ? `"${i.idea_text}" — ${(i.voter_ids || []).length} votes` : 'No ideas submitted yet.';
}
function updateHomeHomeworkCard(session, answers) {
  const el = document.getElementById('openHomeworkBody');
  if (!session) { el.textContent = 'Nothing assigned right now.'; return; }
  const qCount = Array.isArray(session.questions) ? session.questions.length : 0;
  el.textContent = `${session.title} — ${qCount} question${qCount === 1 ? '' : 's'}, ${answers.length} answer${answers.length === 1 ? '' : 's'} so far.`;
}
function updateHomeMeetingCard() {
  const el = document.getElementById('nextMeetingBody');
  const todayKey = ymd(new Date());
  const upcoming = groupEventsCache
    .filter(e => e.is_meeting && e.event_date >= todayKey)
    .sort((a, b) => a.event_date.localeCompare(b.event_date))[0];
  if (!upcoming) { el.textContent = 'No meeting scheduled yet.'; return; }
  const label = new Date(upcoming.event_date + 'T00:00:00').toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' });
  const when = [
    label,
    upcoming.event_time ? formatTime(upcoming.event_time) : null,
    upcoming.location || null
  ].filter(Boolean).join(' · ');
  el.textContent = `${upcoming.title} — ${when}${upcoming.note ? ' (' + upcoming.note + ')' : ''}`;
}

function formatTime(t) {
  // t is like "06:15:00" from Postgres time type
  const [h, m] = t.split(':').map(Number);
  const period = h >= 12 ? 'PM' : 'AM';
  const h12 = h % 12 === 0 ? 12 : h % 12;
  return `${h12}:${String(m).padStart(2, '0')} ${period}`;
}

// ============================================================
// Photos
// ============================================================
document.getElementById('uploadPhotoBtn').addEventListener('click', () => {
  document.getElementById('uploadPhotoInput').click();
});

document.getElementById('uploadPhotoInput').addEventListener('change', async (e) => {
  const file = e.target.files[0];
  e.target.value = '';
  if (!file || !currentProfile) return;
  const statusEl = document.getElementById('photoUploadStatus');
  statusEl.classList.remove('hidden', 'error');
  statusEl.textContent = 'Uploading…';

  try {
    const ext = file.name.split('.').pop();
    const path = `${currentProfile.id}/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;
    const { error: uploadErr } = await sb.storage.from('group-photos').upload(path, file);
    if (uploadErr) throw uploadErr;

    const { error: insertErr } = await sb.from('photos').insert({
      storage_path: path,
      uploaded_by: currentProfile.display_name,
      uploaded_by_id: currentProfile.id,
    });
    if (insertErr) throw insertErr;

    statusEl.classList.add('hidden');
    toast('Photo added!');
    loadPhotos();
  } catch (err) {
    statusEl.textContent = err.message || 'Could not upload photo.';
    statusEl.classList.add('error');
  }
});

async function loadPhotos() {
  const gridEl = document.getElementById('photoGrid');
  const { data, error } = await sb.from('photos').select('*').order('created_at', { ascending: false });
  if (error) { gridEl.innerHTML = `<div class="empty-state">Couldn't load photos.</div>`; return; }
  if (!data || !data.length) {
    gridEl.innerHTML = `<div class="empty-state">No photos yet — add the first one.</div>`;
    return;
  }
  const myId = currentProfile?.id;
  gridEl.innerHTML = data.map(p => {
    const { data: urlData } = sb.storage.from('group-photos').getPublicUrl(p.storage_path);
    return `
    <div class="photo-tile">
      <img src="${urlData.publicUrl}" alt="Group photo" loading="lazy">
      <div class="photo-tile-meta">
        <span>${escapeHtml(p.uploaded_by)}</span>
        ${myId && p.uploaded_by_id === myId ? `<button class="photo-delete" data-photo="${p.id}" data-path="${escapeHtml(p.storage_path)}">Delete</button>` : ''}
      </div>
    </div>`;
  }).join('');
  gridEl.querySelectorAll('.photo-delete').forEach(btn => {
    btn.addEventListener('click', () => deletePhoto(btn.dataset.photo, btn.dataset.path));
  });
}

async function deletePhoto(id, path) {
  await sb.storage.from('group-photos').remove([path]);
  const { error } = await sb.from('photos').delete().eq('id', id);
  if (error) { toast('Could not delete photo.', true); return; }
  toast('Photo removed.');
  loadPhotos();
}

// ============================================================
// Contacts
// ============================================================
document.getElementById('savePhoneBtn').addEventListener('click', async () => {
  if (!currentProfile) return;
  const phone = document.getElementById('myPhoneInput').value.trim();
  const statusEl = document.getElementById('phoneSaveStatus');
  const { error } = await sb.from('profiles').update({ phone: phone || null }).eq('id', currentProfile.id);
  statusEl.classList.remove('hidden', 'error');
  if (error) {
    statusEl.textContent = 'Could not save. Try again.';
    statusEl.classList.add('error');
    return;
  }
  currentProfile.phone = phone || null;
  statusEl.textContent = phone ? 'Saved!' : 'Removed.';
  setTimeout(() => statusEl.classList.add('hidden'), 2000);
  loadContacts();
});

async function loadContacts() {
  const listEl = document.getElementById('contactsList');
  const { data, error } = await sb.from('profiles').select('*').order('display_name', { ascending: true });
  if (error) { listEl.innerHTML = `<div class="empty-state">Couldn't load contacts.</div>`; return; }

  if (currentProfile) {
    document.getElementById('myPhoneInput').value = currentProfile.phone || '';
  }

  const others = (data || []).filter(p => p.id !== currentProfile?.id);
  if (!others.length) {
    listEl.innerHTML = `<div class="empty-state">No one else has joined yet.</div>`;
    return;
  }
  listEl.innerHTML = others.map(p => `
    <div class="contact-card">
      <div class="contact-name">${escapeHtml(p.display_name)}</div>
      ${p.phone
        ? `<a class="contact-phone" href="tel:${escapeHtml(p.phone.replace(/[^\d+]/g, ''))}">${escapeHtml(p.phone)}</a>`
        : `<span class="contact-phone-missing">No number shared yet</span>`}
    </div>`).join('');
}

// ============================================================
// Utilities
// ============================================================
function escapeHtml(str) {
  return String(str ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
